version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/spring-app
hooks:
  BeforeInstall:
    - location: ./dev/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./dev/scripts/start_server.sh
      timeout: 300
      runas: root